version: '2'
services:
  client-connectivity-prod:
    container_name: client-connectivity-prod
    image: elijahahianyo/trade-project:client-connectivity-prod
    ports:
      - 25000:25000
    networks:
      - trade_project

networks:
  trade_project:
#    driver: bridge